#This does not have the parameter definition as this policy does not use any parameters
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sblockhostnetwork
  annotations:
    description: Blocks HostNetwork.
spec:
  crd:
    spec:
      names:
        kind: K8sBlockHostNetwork
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblockhostnetwork

        violation[{"msg": msg, "details": {}}]{
         #input.review.object.kind == "Pod"               #Checks if the kind is "Pod"
         #input.review.object.spec.hostNetwork            #Checks if the hostNetwork is set to true
         #msg := sprintf("HostNetwork is prohibited",[])  #Deny message
        }
