apiVersion: v1
kind: Service							#Kind of object is service
metadata:
  name: kibana
  namespace: kube-logs
  labels:
    app: kibana
spec:
  ports:
  - port: 5601					        	 #To access kibana we shall mention port
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment				                 #Now for Deployment
metadata:
  name: kibana
  namespace: kube-logs
  labels:
    app: kibana
spec:
  replicas: 1						         #Pod needed is 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0     	#Tag of image can be of choice
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL				#This environment variable sets the endpoint and port for Elasticsearch cluster
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
