#This template does not have the parameter defintion as we are not using any parameters in this policy
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sblocklatesttag
  annotations:
    description: Disallows all Services with type NodePort.
spec:
  crd:
    spec:
      names:
        kind: K8sBlockLatestTag
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblocklatesttag
        violation[{"msg": msg, "details": {}}]{
         #input.review.object.kind == "Pod"                           #Checks if the kind is "Pod"
         #imagename := input.review.object.spec.containers[_].image   #Store the image name in a variable
         #endswith(imagename,"latest")                                #Check if it ends with the word "latest" since the image tag will be at the end of the image name
         #msg := "Images with tag the tag \"latest\" is prohibited"   #Deny message
        }
